export const motivationalPhrases = [
  "el exito es hacer lo que amas y poder ayudar a otros a que hagan lo mismo.",
  "La calidad de tu vida está directamente relacionada con la calidad de tus emociones.",
  "El poder no está en el conocimiento, sino en la aplicación del conocimiento.",
  "La clave para la transformación es la mente. Tienes que cambiar tus creencias primero si quieres cambiar tus acciones.",
  "El dinero es solo una herramienta. Puede usarse para bien o para mal. Depende de ti decidir cómo lo usas.",
  "La clave para la riqueza es la gratitud.",
  "La vida paga cualquier precio que tú pidas.",
  "Si no haces lo que temes, el miedo controla tu vida.",
  "La calidad de tu vida está en proporción directa a la cantidad de incertidumbre que puedas tolerar.",
  "El éxito sin cumplimiento es el mayor fracaso.",
  "El camino hacia el éxito está en tomar acción masiva y consistente.",
  "La pasión es energía. Si te sientes apasionado por algo, tendrás éxito en ello.",
  "La gente exitosa hace lo que la gente promedio no está dispuesta a hacer.",
  "El cambio es la ley de la vida, y quienes solo miran al pasado o al presente están seguros de perder el futuro.",
  "El éxito en la vida es el resultado de buenos hábitos.",
  "La gente exitosa hace lo que los demás no están dispuestos a hacer. ¡No desees que sea más fácil, deséalo mejor!",
  "La medida de la vida es la cantidad de momentos extraordinarios que experimentas.",
  "Cuando estés interesado, lo haces cuando sea conveniente. Cuando estás comprometido, no aceptas excusas; solo resultados.",
  "Para tener éxito, tienes que hacer que tus emociones trabajen para ti, no en contra de ti.",
  "El recurso más valioso que tienes es el tiempo.",
  "Lo que hace a alguien especial es su capacidad para superar los obstáculos.",
  "La vida no es lo que te sucede, sino cómo reaccionas ante ello.",
  "El cambio es difícil al principio, desordenado en el medio y hermoso al final.",
  "Tienes que ser consciente de tus decisiones porque tendrás que vivir con sus consecuencias durante bastante tiempo.",
  "El éxito es hacer lo que amas y poder ayudar a otros a que hagan lo mismo.",
  "La calidad de tu vida está directamente relacionada con la calidad de tus emociones.",
  "El poder no está en el conocimiento, sino en la aplicación del conocimiento.",
  "La clave para la transformación es la mente. Tienes que cambiar tus creencias primero si quieres cambiar tus acciones.",
  "El dinero es solo una herramienta. Puede usarse para bien o para mal. Depende de ti decidir cómo lo usas.",
  "La clave para la riqueza es la gratitud.",
  "La vida paga cualquier precio que tú pidas.",
  "Si no haces lo que temes, el miedo controla tu vida.",
  "La calidad de tu vida está en proporción directa a la cantidad de incertidumbre que puedas tolerar.",
  "El éxito sin cumplimiento es el mayor fracaso.",
  "El camino hacia el éxito está en tomar acción masiva y consistente.",
  "La pasión es energía. Si te sientes apasionado por algo, tendrás éxito en ello.",
  "La gente exitosa hace lo que la gente promedio no está dispuesta a hacer.",
  "El cambio es la ley de la vida, y quienes solo miran al pasado o al presente están seguros de perder el futuro.",
  "El éxito en la vida es el resultado de buenos hábitos.",
  "La gente exitosa hace lo que los demás no están dispuestos a hacer. ¡No desees que sea más fácil, deséalo mejor!",
  "La medida de la vida es la cantidad de momentos extraordinarios que experimentas.",
  "Cuando estés interesado, lo haces cuando sea conveniente. Cuando estás comprometido, no aceptas excusas; solo resultados.",
  "Para tener éxito, tienes que hacer que tus emociones trabajen para ti, no en contra de ti.",
  "El recurso más valioso que tienes es el tiempo.",
  "Lo que hace a alguien especial es su capacidad para superar los obstáculos.",
  "La vida no es lo que te sucede, sino cómo reaccionas ante ello.",
  "El cambio es difícil al principio, desordenado en el medio y hermoso al final.",
  "Tienes que ser consciente de tus decisiones porque tendrás que vivir con sus consecuencias durante bastante tiempo.",
  "La vida es demasiado corta para vivirla pequeña.",
  "El éxito no es hacerlo todo bien, sino hacerlo todo y aprender de tus errores.",
  "La calidad de tu vida está determinada por la calidad de tus preguntas.",
  "Si quieres cambiar tu vida, debes estar dispuesto a cambiar tu mente.",
  "La decisión es el punto de partida de todos los logros.",
  "El propósito de la vida es vivirla, saborearla y alcanzar tus sueños.",
  "La verdadera libertad comienza en la mente.",
  "El progreso es imposible sin el cambio, y aquellos que no pueden cambiar sus mentes no pueden cambiar nada.",
  "El éxito sin significado es el verdadero fracaso.",
  "Tu pasado no iguala tu potencial.",
  "La excelencia no es una habilidad, es una actitud.",
  "La verdadera medida de tu riqueza es cuánto valdrías si lo perdieras todo mañana.",
  "La confianza nace de la acción, no del pensamiento.",
  "La única cosa que te detiene son las historias que te sigues contando a ti mismo.",
  "La vida es una danza entre lo que deseamos y lo que nos sucede.",
  "Cambia tu expectativa por apreciación y toda tu vida cambiará al instante.",
  "El amor es el idioma que todos entienden.",
  "El éxito es aprender a fracasar sin perder el entusiasmo.",
  "El camino hacia cualquier objetivo comienza con la decisión de intentarlo.",
  "La vida no es sobre encontrar a uno mismo, sino sobre crearse a uno mismo.",
  "La gente exitosa hace lo que sea necesario para tener éxito. Los demás hacen lo que es conveniente.",
  "Las palabras tienen poder. Habla palabras de amor y éxito.",
  "La paciencia es una virtud, y el momento adecuado es un misterio.",
  "Las limitaciones viven solo en nuestra mente. Pero si usamos nuestra imaginación, nuestras posibilidades se vuelven ilimitadas.",
  "El éxito es un 20% de habilidad y un 80% de psicología.",
  "El compromiso es el puente entre las metas y la realidad.",
  "La calidad de tu vida depende de la calidad de tus relaciones.",
  "Tú eres el amo de tu destino y el capitán de tu alma.",
  "El miedo es una emoción. El miedo es real, pero nosotros elegimos el miedo o el coraje.",
  "El conocimiento no es poder, es solo potencial. El poder viene de la acción.",
  "La vida es realmente generosa con quienes la aprovechan al máximo.",
  "No importa cómo te sientas. Levántate, vístete, aparece y nunca te rindas.",
  "El éxito no es lo que tienes, sino quien te has convertido mientras lo obtienes.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "El cambio es la ley de la vida, y aquellos que miran solo al pasado o al presente están seguros de perder el futuro.",
  "La clave para una vida extraordinaria es eliminar lo ordinario.",
  "El éxito se trata de hacer lo correcto, no lo fácil.",
  "La acción es la clave para cualquier éxito.",
  "La clave es aprender de los errores y nunca dejar de mejorar.",
  "Tu vida mejora cuando tomas decisiones enfocadas y consistentes.",
  "El entusiasmo es la chispa que enciende el fuego del logro.",
  "El primer paso para el cambio es conciencia. El segundo paso es aceptación.",
  "La vida no se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia.",
  "Las personas exitosas hacen lo que sea necesario para tener éxito, y luego hacen lo que les gusta.",
  "No puedes tener un millón de dólares de vida con una mentalidad de mil dólares.",
  "La mayor revolución de tu vida es aprender a controlar tu diálogo interno.",
  "La recompensa por el trabajo bien hecho es la oportunidad de hacer más trabajo bien hecho.",
  "No te preocupes por fallar, preocúpate por las posibilidades que pierdes cuando no lo intentas.",
  "El éxito en la vida es el resultado de buenos hábitos.",
  "La calidad de tu vida está en proporción directa a la cantidad de incertidumbre que puedas tolerar.",
  "El cambio es la ley de la vida, y quienes solo miran al pasado o al presente están seguros de perder el futuro.",
  "El éxito en la vida es el resultado de buenos hábitos.",
  "La gente exitosa hace lo que los demás no están dispuestos a hacer. ¡No desees que sea más fácil, deséalo mejor!",
  "La medida de la vida es la cantidad de momentos extraordinarios que experimentas.",
  "Cuando estés interesado, lo haces cuando sea conveniente. Cuando estás comprometido, no aceptas excusas; solo resultados.",
  "Para tener éxito, tienes que hacer que tus emociones trabajen para ti, no en contra de ti.",
  "El recurso más valioso que tienes es el tiempo.",
  "Lo que hace a alguien especial es su capacidad para superar los obstáculos.",
  "La vida no es lo que te sucede, sino cómo reaccionas ante ello.",
  "El cambio es difícil al principio, desordenado en el medio y hermoso al final.",
  "Tienes que ser consciente de tus decisiones porque tendrás que vivir con sus consecuencias durante bastante tiempo.",
  "La vida es demasiado corta para vivirla pequeña.",
  "El éxito no es hacerlo todo bien, sino hacerlo todo y aprender de tus errores.",
  "La calidad de tu vida está determinada por la calidad de tus preguntas.",
  "Si quieres cambiar tu vida, debes estar dispuesto a cambiar tu mente.",
  "La decisión es el punto de partida de todos los logros.",
  "El propósito de la vida es vivirla, saborearla y alcanzar tus sueños.",
  "La verdadera libertad comienza en la mente.",
  "El progreso es imposible sin el cambio, y aquellos que no pueden cambiar sus mentes no pueden cambiar nada.",
  "El éxito sin significado es el verdadero fracaso.",
  "Tu pasado no iguala tu potencial.",
  "La excelencia no es una habilidad, es una actitud.",
  "La verdadera medida de tu riqueza es cuánto valdrías si lo perdieras todo mañana.",
  "La confianza nace de la acción, no del pensamiento.",
  "La única cosa que te detiene son las historias que te sigues contando a ti mismo.",
  "La vida es una danza entre lo que deseamos y lo que nos sucede.",
  "Cambia tu expectativa por apreciación y toda tu vida cambiará al instante.",
  "El amor es el idioma que todos entienden.",
  "El éxito es aprender a fracasar sin perder el entusiasmo.",
  "El camino hacia cualquier objetivo comienza con la decisión de intentarlo.",
  "La vida no es sobre encontrar a uno mismo, sino sobre crearse a uno mismo.",
  "La gente exitosa hace lo que sea necesario para tener éxito. Los demás hacen lo que es conveniente.",
  "Las palabras tienen poder. Habla palabras de amor y éxito.",
  "La paciencia es una virtud, y el momento adecuado es un misterio.",
  "Las limitaciones viven solo en nuestra mente. Pero si usamos nuestra imaginación, nuestras posibilidades se vuelven ilimitadas.",
  "El éxito es un 20% de habilidad y un 80% de psicología.",
  "El compromiso es el puente entre las metas y la realidad.",
  "La calidad de tu vida depende de la calidad de tus relaciones.",
  "Tú eres el amo de tu destino y el capitán de tu alma.",
  "El miedo es una emoción. El miedo es real, pero nosotros elegimos el fear o el coraje.",
  "El conocimiento no es poder, es solo potencial. El poder viene de la acción.",
  "La vida es realmente generosa con quienes la aprovechan al máximo.",
  "No importa cómo te sientas. Levántate, vístete, aparece y nunca te rindas.",
  "El éxito no es lo que tienes, sino quien te has convertido mientras lo obtienes.",
  "La única manera de hacer un gran trabajo es amar lo que haces.",
  "El cambio es la ley de la vida, y aquellos que miran solo al pasado o al presente están seguros de perder el futuro.",
  "La clave para una vida extraordinaria es eliminar lo ordinario.",
  "El éxito se trata de hacer lo correcto, no lo fácil.",
  "La acción es la clave para cualquier éxito.",
  "La clave es aprender de los errores y nunca dejar de mejorar.",
  "Tu vida mejora cuando tomas decisiones enfocadas y consistentes.",
  "El entusiasmo es la chispa que enciende el fuego del logro.",
  "El primer paso para el cambio es conciencia. El segundo paso es aceptación.",
  "La vida no se trata de esperar a que pase la tormenta, sino de aprender a bailar bajo la lluvia.",
  "Las personas exitosas hacen lo que sea necesario para tener éxito, y luego hacen lo que les gusta.",
  "No puedes tener un millón de dólares de vida con una mentalidad de mil dólares.",
  "La mayor revolución de tu vida es aprender a controlar tu diálogo interno.",
  "La recompensa por el trabajo bien hecho es la oportunidad de hacer más trabajo bien hecho.",
  "No te preocupes por fallar, preocúpate por las posibilidades que pierdes cuando no lo intentas.",
  "El éxito es hacer lo que amas y poder ayudar a otros a que hagan lo mismo.",
  "La calidad de tu vida está directamente relacionada con la calidad de tus emociones.",
  "El poder no está en el conocimiento, sino en la aplicación del conocimiento.",
  "La clave para la transformación es la mente. Tienes que cambiar tus creencias primero si quieres cambiar tus acciones.",
  "El dinero es solo una herramienta. Puede usarse para bien o para mal. Depende de ti decidir cómo lo usas.",
  "La clave para la riqueza es la gratitud.",
  "La vida paga cualquier precio que tú pidas.",
  "Si no haces lo que temes, el miedo controla tu vida.",
  "La calidad de tu vida está en proporción directa a la cantidad de incertidumbre que puedas tolerar.",
  "El éxito sin cumplimiento es el mayor fracaso.",
  "El camino hacia el éxito está en tomar acción masiva y consistente.",
  "La pasión es energía. Si te sientes apasionado por algo, tendrás éxito en ello.",
  "La gente exitosa hace lo que la gente promedio no está dispuesta a hacer.",
  "El cambio es la ley de la vida, y quienes solo miran al pasado o al presente están seguros de perder el futuro.",
  "El éxito en la vida es el resultado de buenos hábitos.",
  "La gente exitosa hace lo que los demás no están dispuestos a hacer. ¡No desees que sea más fácil, deséalo mejor!",
  "La medida de la vida es la cantidad de momentos extraordinarios que experimentas.",
  "Cuando estés interesado, lo haces cuando sea conveniente. Cuando estás comprometido, no aceptas excusas; solo resultados.",
  "Para tener éxito, tienes que hacer que tus emociones trabajen para ti, no en contra de ti.",
  "El recurso más valioso que tienes es el tiempo.",
  "Lo que hace a alguien especial es su capacidad para superar los obstáculos.",
  "La vida no es lo que te sucede, sino cómo reaccionas ante ello.",
  "El cambio es difícil al principio, desordenado en el medio y hermoso al final.",
  "Tienes que ser consciente de tus decisiones porque tendrás que vivir con sus consecuencias durante bastante tiempo.",
  "La vida es demasiado corta para vivirla pequeña.",
  "El éxito no es hacerlo todo bien, sino hacerlo todo y aprender de tus errores.",
  "La calidad de tu vida está determinada por la calidad de tus preguntas.",
  "Si quieres cambiar tu vida, debes estar dispuesto a cambiar tu mente.",
  "La decisión es el punto de partida de todos los logros.",
  "El propósito de la vida es vivirla, saborearla y alcanzar tus sueños.",
  "La verdadera libertad comienza en la mente.",
  "El progreso es imposible sin el cambio, y aquellos que no pueden cambiar sus mentes no pueden cambiar nada.",
  "El éxito sin significado es el verdadero fracaso.",
  "Tu pasado no iguala tu potencial.",
  "La excelencia no es una habilidad, es una actitud.",
  "La verdadera medida de tu riqueza es cuánto valdrías si lo perdieras todo mañana.",
  "La confianza nace de la acción, no del pensamiento.",
  "La única cosa que te detiene son las historias que te sigues contando a ti mismo.",
  "La vida es una danza entre lo que deseamos y lo que nos sucede.",
  "Cambia tu expectativa por apreciación y toda tu vida cambiará al instante.",
  "El amor es el idioma que todos entienden.",
  "El éxito es aprender a fracasar sin perder el entusiasmo.",
  "El camino hacia cualquier objetivo comienza con la decisión de intentarlo.",
  "La vida no es sobre encontrar a uno mismo, sino sobre crearse a uno mismo.",
  "La gente exitosa hace lo que sea necesario para tener éxito. Los demás hacen lo que es conveniente.",
  "Las palabras tienen poder. Habla palabras de amor y éxito.",
  "La paciencia es una virtud, y el momento adecuado es un misterio.",
  "Las limitaciones viven solo en nuestra mente. Pero si usamos nuestra imaginación, nuestras posibilidades se vuelven ilimitadas.",
  "El éxito es un estado mental.",
  "La vida te da lo que tú le pides.",
  "La gente exitosa se levanta temprano y trabaja en lo que cree.",
  "El fracaso es la manera en que el universo te está preparando para algo más grande.",
  "El progreso es imposible sin el cambio.",
  "El dinero es solo una medida del valor que has proporcionado.",
  "El propósito de la vida es crecer y contribuir más allá de uno mismo.",
  "Elige tus pensamientos sabiamente. Son el inicio de tus acciones.",
  "El éxito es hacer lo que amas y ser capaz de compartirlo con los demás.",
  "El camino hacia cualquier meta comienza con un primer paso.",
  "La clave para la riqueza es gastar menos de lo que ganas y invertir la diferencia.",
  "La decisión de enfrentar tus miedos es el primer paso hacia el éxito.",
  "La calidad de tu vida está directamente relacionada con la calidad de tus relaciones.",
  "El cambio es difícil al principio, confuso en el medio y hermoso al final.",
  "La clave para la felicidad es la progresión constante y el crecimiento personal.",
  "El éxito es un viaje, no un destino.",
  "Las palabras tienen poder. Habla palabras de amor y esperanza.",
  "El fracaso es una lección en camino al éxito.",
  "La clave para el éxito es tomar decisiones audaces y luego comprometerse a ellas.",
  "El amor y la generosidad son las llaves para una vida plena.",
  "La acción crea resultados, la inacción crea excusas.",
  "Elige tus creencias con cuidado. Ellas crean tu realidad.",
  "La autodisciplina es el puente entre las metas y los logros.",
  "El éxito no es la clave de la felicidad, la felicidad es la clave del éxito.",
  "La vida es demasiado corta para vivirla sin pasión.",
  "La persistencia es la clave para superar los obstáculos.",
  "El éxito se trata de aprender a fracasar hacia adelante.",
  "La excelencia es un hábito, no un acto.",
  "El miedo es solo una emoción. No dejes que te controle.",
  "La calidad de tu vida depende de la calidad de tus preguntas.",
  "La mayoría de las personas sobreestiman lo que pueden hacer en un año y subestiman lo que pueden hacer en diez años.",
  "El éxito no es para los débiles de corazón.",
  "La vida te recompensará si te atreves a tomar riesgos.",
  "La confianza es el resultado de la preparación y la práctica.",
  "El cambio es una oportunidad para crecer y mejorar.",
  "El dinero no puede comprar la felicidad, pero puede comprar la libertad para buscarla.",
  "La vida es un regalo, y cada día es una oportunidad para aprovecharlo al máximo.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "El futuro pertenece a aquellos que creen en la belleza de sus sueños.",
  "El éxito no tiene un camino único; es una montaña que se puede escalar desde cualquier lado.",
  "La verdadera riqueza es tener tiempo y libertad para vivir la vida a tu manera.",
  "La pasión es la fuerza que te impulsa a superar cualquier obstáculo.",
  "El cambio comienza con la voluntad de intentarlo.",
  "La vida es un regalo, y cada día es una oportunidad para hacerlo memorable.",
  "El éxito no es un destino, es un viaje que nunca termina.",
  "La actitud determina la altitud.",
  "El miedo es una ilusión; el coraje es real.",
  "La vida es demasiado corta para desperdiciarla en preocupaciones y quejas.",
  "La clave para el éxito es tomar acción con determinación y persistencia.",
];

export const highScoreExample = [{name:"Marian",score:50},{name:"Leon",score:80},{name:"Jacobo",score:40},{name:"Ranma",score:20},{name:"Batuzai",score:10},{name:"Reinaldo",score:60},{name:"Gerard",score:2},{name:"Samid",score:40},{name:"Samid",score:40},{name:"Samid",score:40},{name:"Samid",score:40}]
